### ISSUE TITLE
API "create" Endpoint not in line with RESTful Standard 

### ISSUE THREAD

**Issue by LGR3VE** [r-wittmann/DI-project#1]
The POST routes for creating a list and item are not according to the RESTful naming conventions.

See 2.4 at: [https://restfulapi.net/resource-naming/](https://restfulapi.net/resource-naming/)

HTTP POST http://localhost/lists
HTTP POS http://localhost/items
_instead of
HTTP POST http://localhost/lists/create
HTTP POS http://localhost/items/create_

**Comment by r-wittmann** [comment]
Thank you for making me aware of that. Would you be willing to make a pull request? I will happily accept it 😉
